import { InferGetServerSidePropsType } from 'next'
import Head from 'next/head'

export default function Slug(props: InferGetServerSidePropsType<typeof getServerSideProps>) {
  console.log('Slug', props)
  return (
    <>
      <Head>
        <title>Slug</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {props.slug.text}
      </main>
    </>
  )
}

export const getServerSideProps = async () => {
  return {
    props: { slug: {text: 'Slug'} },
  }
}
