import { InferGetServerSidePropsType } from 'next'
import Head from 'next/head'
import Link from 'next/link'

export default function Home(props: InferGetServerSidePropsType<typeof getServerSideProps>) {
  console.log('Home', props)
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>{props.home.text}</div>
        <div><Link href="/1">/1 (Runtime error occurs)</Link></div>
        <div><Link href="/12">/12 (Runtime error occurs)</Link></div>
        <div><Link href="/123">/123 (Runtime error occurs)</Link></div>
        <div><Link href="/1234">/1234 (Runtime error occurs)</Link></div>
        <div><Link href="/12345">/12345 (No runtime errors)</Link></div>
        <div><Link href="/123456">/123456 (No runtime errors)</Link></div>
        <div><Link href="/1234567">/1234567 (No runtime errors)</Link></div>
        <div><Link href="/12345678">/12345678 (No runtime errors)</Link></div>
        <div><Link href="/123456789">/123456789 (No runtime errors)</Link></div>
      </main>
    </>
  )
}

export const getServerSideProps = async () => {
  return {
    props: { home: { text: 'Home' } },
  }
}
